version: '3'
tasks:
  run:
    desc: Run blog locally
    cmd: ./tools/run.sh

  build:
    desc: Build blog
    cmds:
      - bundle exec jekyll b -d _site

  test:
    desc: Run tests
    cmd: ./tools/test.sh
